const products = [
  {
    id: 1,
    name: "Apple iMac 27, 1TB HDD, Retina 5K",
    price: 169999,
    originalPrice: 199999,
    discount: "35% OFF",
    rating: 5.0,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Desktops/Images/311754_0_p4etiv.png",
    isBestSeller: false,
    brand: "Apple",
  },
  {
    id: 2,
    name: "Apple iPhone17 Pro",
    price: 89999,
    originalPrice: 100000,
    discount: "15% OFF",
    rating: 4.0,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/317417_0_7ISiBcc4Y.png?updatedAt=1757529273198",
    isBestSeller: true,
    brand: "Apple",
  },
  {
    id: 3,
    name: "Samsung S25 Ultra",
    price: 109999,
    originalPrice: 130000,
    discount: "35% OFF",
    rating: 4.9,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/313337_0_fabi1f.png",
    isBestSeller: true,
    brand: "Samsung",
  },
  {
    id: 4,
    name: "NOTHING PHONE 3A",
    price: 59999,
    originalPrice: 89999,
    discount: "25% OFF",
    rating: 4.2,
    image:
      "https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/316739_0_azriyg.png",
    isBestSeller: true,
    brand: "Nothing",
  },
  {
    id: 5,
    name: "Apple MacBook Air M3 (13.6 inch)",
    price: 99900,
    originalPrice: 114900,
    discount: "13% OFF",
    rating: 4.8,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/305382_uvrdrb.png",
    isBestSeller: true,
    brand: "Apple",
  },
  {
    id: 6,
    name: "Lenovo LOQ Gaming Laptop Intel i7",
    price: 80990,
    originalPrice: 104990,
    discount: "23% OFF",
    rating: 4.5,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/320287_0_1EXbo1XtT.png",
    isBestSeller: false,
    brand: "Lenovo",
  },
  {
    id: 7,
    name: "DELL 15 Intel Core i5 Thin & Light Laptop",
    price: 63990,
    originalPrice: 79990,
    discount: "20% OFF",
    rating: 4.3,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/318514_0_n-v0vk2v5.png",
    isBestSeller: false,
    brand: "Dell",
  },
  {
    id: 8,
    name: "HP OmniBook 3 AMD Ryzen AI 5 Laptop",
    price: 61990,
    originalPrice: 74990,
    discount: "17% OFF",
    rating: 4.1,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/316469_0_VYPHpdhKw.png",
    isBestSeller: false,
    brand: "HP",
  },
  {
    id: 9,
    name: "Sony ULT WEAR ANC Headphones",
    price: 14990,
    originalPrice: 19990,
    discount: "25% OFF",
    rating: 4.7,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Entertainment/Headphones%20and%20Earphones/Images/307142_lfn2vt.png",
    isBestSeller: true,
    brand: "Sony",
  },
  {
    id: 10,
    name: "Apple iPad 11 inch Wi-Fi 128GB",
    price: 34900,
    originalPrice: 39900,
    discount: "13% OFF",
    rating: 4.6,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Tablets%20and%20iPads/Images/314071_0_tn5yfm.png",
    isBestSeller: true,
    brand: "Apple",
  },
  {
    id: 11,
    name: "Samsung QLED 4K Smart TV 43 inch",
    price: 42990,
    originalPrice: 61990,
    discount: "31% OFF",
    rating: 4.4,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Entertainment/Television/Images/315353_0_F2WBs1f8t.png",
    isBestSeller: false,
    brand: "Samsung",
  },
  {
    id: 12,
    name: "OnePlus Nord Buds 3r TWS Earbuds",
    price: 1799,
    originalPrice: 2999,
    discount: "40% OFF",
    rating: 4.0,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Entertainment/Headphones%20and%20Earphones/Images/318486_0_A_bf0wbZR.png",
    isBestSeller: false,
    brand: "OnePlus",
  },
  {
    id: 12,
    name: "OnePlus Nord Buds 3r TWS Earbuds",
    price: 1799,
    originalPrice: 2999,
    discount: "40% OFF",
    rating: 4.3,
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Headphones%20And%20Earphones/Images/318487_0_Tp7jv81qAM.png?updatedAt=1756454924387?tr=w-400",
    isBestSeller: false,
    brand: "OnePlus",
  }
];
export default products;
